---
version: "3.8"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.12.10
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,iam,sts
    ports:
      - '4566:4566'
    volumes:
      - /docker-entrypoint-initaws.d

  consul:
    container_name: consul
    image: consul:1.9.5
    ports:
      - "8500:8500/tcp"
    environment:
      CONSUL_LOCAL_CONFIG: >
        {"acl": {"enabled": true, "tokens": {"master": "foo"} }}

  vault:
    container_name: vault
    image: vault:1.3.2
    ports:
      - "8200:8200"
    links:
      - consul:consul
      - localstack:localstack
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=foo
    cap_add:
      - IPC_LOCK

